cask_args appdir: '/Applications'

# Packages
brew "ctags"
brew "htop"
brew "n"
brew "python"
brew "postgresql"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby-build"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "wget"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Applications
tap "caskroom/cask"
# cask "java8"
# cask "iterm2"

# Fonts
tap "caskroom/fonts"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-meslo-nerd-font-mono"

# Zsh Themes
tap "sambadevi/powerlevel9k"
brew "powerlevel9k"
