cask_args appdir: '/Applications'
tap "homebrew/bundle"
tap "homebrew/core"

# Packages
brew "ctags"
brew "curl"
brew "fzf"
brew "git"
brew "go"
brew "htop"
brew "n"
brew "postgresql"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "wget"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Fonts
tap "caskroom/fonts"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-meslo-nerd-font-mono"

# Zsh Themes
tap "sambadevi/powerlevel9k"
brew "powerlevel9k"
brew "starship"

# Applications
# tap "caskroom/cask"
# cask "java8"
# cask "iterm2"
