[notifications]
toast_duration_secs = 8

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[account]
is_settings_sync_enabled = true

[appearance]
spacing = "normal"

[appearance.panes]
focus_pane_on_hover = false
should_dim_inactive_panes = true

[appearance.text]
ligature_rendering_enabled = true
match_notebook_to_monospace_font_size = true
font_size = 13.0
match_ai_font = false
notebook_font_size = 14.0
font_name = "FiraCode Nerd Font Mono"
ai_font_name = "FiraCode Nerd Font Mono"
use_thin_strokes = "always"

[appearance.window]
zoom_level = 100
open_windows_at_custom_size = false
override_opacity = 63
override_blur = 17
left_panel_visibility_across_tabs = true

[appearance.vertical_tabs]
view_mode = "compact"
enabled = true
compact_subtitle = "working_directory"
display_granularity = "tabs"
primary_info = "command"
tab_item_mode = "focused_session"

[appearance.full_screen_apps]
alt_screen_padding = { custom = { uniform_padding = 0.0 } }

[appearance.tabs]
workspace_decoration_visibility = "always_show"

[appearance.themes]
theme = "dracula"
system_theme = false

[appearance.icon]
app_icon = "neon"

[appearance.blocks]
show_block_dividers = true

[terminal]
osc52_clipboard_access = "write_only"
use_audible_bell = true

[terminal.input]
input_box_type_setting = "universal"
completions_open_while_typing = false
alias_expansion_enabled = true
honor_ps1 = false

[terminal.input.extra_meta_keys]
left_alt = true
right_alt = false

[agents]
cloud_conversation_storage_enabled = true

[agents.profiles]
agent_mode_execute_readonly_commands = true
agent_mode_coding_permissions = "always_allow_reading"

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.input]
nld_in_terminal_enabled = true

[agents.warp_agent.active_ai]
intelligent_autosuggestions_enabled = false
enabled = false

[agents.warp_agent.other]
agent_attribution_enabled = false
should_show_oz_updates_in_zero_state = false
should_render_use_agent_toolbar_for_user_commands = false

[agents.voice]
voice_input_enabled = false

[agents.third_party]
should_render_cli_agent_toolbar = false

[accessibility]
accessibility_verbosity = "concise"

[privacy]
telemetry_enabled = false
crash_reporting_enabled = false
custom_secret_regex_list = [
  { name = "IPv4 Address", pattern = '\b((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}\b' },
  {
    name = "IPv6 Address",
    pattern = '\b((([0-9A-Fa-f]{1,4}:){1,6}:)|(([0-9A-Fa-f]{1,4}:){7}))([0-9A-Fa-f]{1,4})\b',
  },
  { name = "Slack App Token", pattern = '\bxapp-[0-9]+-[A-Za-z0-9_]+-[0-9]+-[a-f0-9]+\b' },
  { name = "Phone Number", pattern = '\b(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\b' },
  {
    name = "AWS Access ID",
    pattern = '\b(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}\b',
  },
  {
    name = "MAC Address",
    pattern = '\b((([a-zA-z0-9]{2}[-:]){5}([a-zA-z0-9]{2}))|(([a-zA-z0-9]{2}:){5}([a-zA-z0-9]{2})))\b',
  },
  { name = "Google API Key", pattern = '\bAIza[0-9A-Za-z-_]{35}\b' },
  { name = "Google OAuth ID", pattern = '\b[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com\b' },
  { name = "GitHub Classic Personal Access Token", pattern = '\bghp_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub Fine-Grained Personal Access Token", pattern = '\bgithub_pat_[A-Za-z0-9_]{82}\b' },
  { name = "GitHub OAuth Access Token", pattern = '\bgho_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub User-to-Server Token", pattern = '\bghu_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub Server-to-Server Token", pattern = '\bghs_[A-Za-z0-9_]{36}\b' },
  { name = "Stripe Key", pattern = '\b(?:r|s)k_(test|live)_[0-9a-zA-Z]{24}\b' },
  { name = "Firebase Auth Domain", pattern = '\b([a-z0-9-]){1,30}(\.firebaseapp\.com)\b' },
  { name = "JWT", pattern = '\b(ey[a-zA-z0-9_\-=]{10,}\.){2}[a-zA-z0-9_\-=]{10,}\b' },
  { name = "OpenAI API Key", pattern = '\bsk-[a-zA-Z0-9]{48}\b' },
  { name = "Anthropic API Key", pattern = '\bsk-ant-api\d{0,2}-[a-zA-Z0-9\-]{80,120}\b' },
  { name = "Generic SK API Key", pattern = '\bsk-[a-zA-Z0-9\-]{10,100}\b' },
  { name = "Fireworks API Key", pattern = '\bfw_[a-zA-Z0-9]{24}\b' },
]

[general]
default_session_mode = "terminal"
quit_on_last_window_closed = true

[code]

[code.indexing]
agent_mode_codebase_context_auto_indexing = true

[text_editing]
vim_mode_enabled = true
